trigger:
- master

jobs:
- job: BuildTest
  displayName: 'Ubuntu 18.04'
  pool: 'HwangsaeulUbuntu1804'
  steps:
  - bash: |
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository ppa:hwangsaeul/nightly
      sudo apt-get update
      sudo apt-get install -y \
        gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
        gstreamer1.0-libav \
        libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgaeguli-dev libchamge-dev

    displayName: 'Installing GStreamer 1.16 from hwangsaeul Nightly PPA'

  - bash: |
      pip3 install --user meson ninja
    displayName: 'Preparing meson and ninja'

  - bash: |
      meson build 
    displayName: 'Meson build'

  - bash: |
      ninja -C build 
    displayName: 'Ninja build'

  - bash: |
      meson test -C build -v --setup debug
    displayName: 'Test'
