trigger:
- master

jobs:
- job: BuildTest
  displayName: 'Ubuntu 18.04'
  pool: 'Ubuntu1804'
  steps:
  - bash: |
      sudo apt-get install software-properties-common
      sudo add-apt-repository ppa:hwangsaeul/ppa
      sudo apt-get update
    displayName: 'Adding hwangsaeul PPA'

  - bash: |
      sudo apt-get install libgaeguli-dev
    displayName: 'Installing dependencies'

  - bash: |
      pip3 install --user meson ninja
    displayName: 'Preparing Meson'

  - bash: |
      meson build 
    displayName: 'Meson build'

  - bash: |
      ninja -C build 
    displayName: 'Ninja build'
